baseURL = "http://miguelmartin.org"
languageCode = "en"
title = "Miguel Martin"
theme = "hugo-initio"


[params]
    name = "Dr. Miguel Martin"
    description = "Postdoctoral Research Fellow"
    email = "M.Martin@tudelft.nl"
    phone = "+31644381309"
    address = "Julianalaan 134, 2628 BL, Delft, Netherlands"
    year = 2024
    avatar = "images/Miguel_Martin.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/background.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 23, 2024"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showAbout = true
    showBackground = true	
    showProjects = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 2

[[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 3

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/cv_miguel_martin.pdf"
  weight = 5

[[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/news/"
    weight = 6

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"


[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/miguel-martin-30b621208"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/migmartin"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "scopus"
	url = "https://www.scopus.com/authid/detail.uri?authorId=56037196400"
    icon = "fab fa-google"
    footer = true
    sharethis = false
    network = "scopus"
[[params.social]]
	title = "YouTube"
	url = "https://www.youtube.com/channel/UCNomvpB-Vr5yE--wM0e4xvA"
    icon = "fab fa-youtube"
    footer = true
    sharethis = false
    network = "google"
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
