baseURL = "http://miguelmartin.org"
languageCode = "en"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"

[params]
    name = "Dr. Miguel Martin"
    description = "Postdoctoral Research Fellow"
    email = "M.Martin@tudelft.nl"
    phone = "+1-412-475-1521"
    address = "119 Forbes Ave, 5000 Porter Hall, PA 15213"
    year = 2024
    avatar = "images/Miguel_Martin.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/background.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 23, 2024"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showAbout = true
	showBackground = true	
    showProjects = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "Awards"
    url = "/awards/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"


[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/miguel-martin-30b621208"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/migmartin"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google scholar"
	url = "https://scholar.google.com/citations?hl=en&user=60sstlEAAAAJ"
    icon = "fab fa-google"
    footer = true
    sharethis = false
    network = "google"
[[params.social]]
	title = "YouTube"
	url = "https://www.youtube.com/channel/UCNomvpB-Vr5yE--wM0e4xvA"
    icon = "fab fa-youtube"
    footer = true
    sharethis = false
    network = "google"
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
